In [2]:
import numpy as np

In [5]:
#16. How to add a border (filled with 0's) around an existing array? 
x = np.ones((3,3))
print("Original array")
print(x)

x = np.pad(x, pad_width=1, mode= 'constant', constant_values=0)
print("Modified array")
print(x)

Original array
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Modified array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
#17. What is the result of the following expression? 
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

In [7]:
#18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 
x = np.diag([1,2,3,4])
print(x)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [11]:
#19. Create a 8x8 matrix and fill it with a checkerboard pattern 
x = np.zeros((8,8), dtype=int)
x[1::2, ::2] = 1
x[::2, 1::2] = 1

print("Checkerboard pattern: ")
print(x)

Checkerboard pattern: 
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
# 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?



In [ ]:
#21. Create a checkerboard 8x8 matrix using the tile function


In [14]:
#22. Normalize a 5x5 random matrix
x = np.random.rand(5,5)
print("Initial Array")
print(x)

col_mean = np.mean(x, axis=0)
arr_nomalized = (x - col_mean) / np.std(x, axis=0)
print("Nomalized Array")
print(arr_nomalized)

Initial Array
[[0.82353468 0.8795865  0.72648099 0.34376596 0.21428722]
 [0.71259616 0.597645   0.77799308 0.01856424 0.31684927]
 [0.81198511 0.93758443 0.95302771 0.34537917 0.58050731]
 [0.72231954 0.84418214 0.19288621 0.47013375 0.5729531 ]
 [0.96860469 0.31979192 0.41793001 0.55018372 0.0533009 ]]
Nomalized Array
[[ 1.70591561e-01  7.13947174e-01  4.14576425e-01 -1.01465883e-02
  -6.49843707e-01]
 [-1.03279164e+00 -5.14723877e-01  6.03870802e-01 -1.80402912e+00
  -1.49820214e-01]
 [ 4.53099336e-02  9.66696006e-01  1.24708046e+00 -1.24774372e-03
   1.13559890e+00]
 [-9.27319166e-01  5.59658764e-01 -1.54625443e+00  6.86925301e-01
   1.09876967e+00]
 [ 1.74420931e+00 -1.72557807e+00 -7.19273258e-01  1.12849815e+00
  -1.43470465e+00]]


In [ ]:
#23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)


In [24]:
#24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
x = np.random.random((5,3))
print("First array")
print(x)

y = np.random.random((3,2))
print("Second array")
print(y)

z = np.dot(x,y)
print("Product of x and y")
print(z)

First array
[[0.56846289 0.07565985 0.34342202]
 [0.27788772 0.58646877 0.4532734 ]
 [0.23125475 0.77407691 0.9318598 ]
 [0.76855575 0.67647542 0.47267076]
 [0.94282881 0.18700841 0.70813876]]
Second array
[[0.77142762 0.10460345]
 [0.56754622 0.10426524]
 [0.03986665 0.99613292]]
Product of x and y
[[0.49515952 0.40944585]
 [0.56528889 0.54173688]
 [0.65487086 1.03315558]
 [0.99566001 0.62176936]
 [0.86169123 0.82352195]]


In [27]:
#25. Given a 1D array, negate all elements which are between 3 and 8, in place.
arr = np.arange(11)
print(arr)

m = (arr>2) & (arr<8)
arr[m] *= -1

print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2 -3 -4 -5 -6 -7  8  9 10]


In [28]:
#26. What is the output of the following script? (★☆☆)
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [ ]:
#27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

In [29]:
#28. What are the result of the following expressions?
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\User 1\AppData\Local\Temp\ipykernel_14596\1713965767.py:2: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
C:\Users\User 1\AppData\Local\Temp\ipykernel_14596\1713965767.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
C:\Users\User 1\AppData\Local\Temp\ipykernel_14596\1713965767.py:4: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

In [31]:
#29. How to round away from zero a float array ?
arr = np.array([-2.5, -1.8,0.3,1.5])
print(arr)

arr1 = np.abs(arr)     #use of absolute fuction
print(arr1)

[-2.5 -1.8  0.3  1.5]
[2.5 1.8 0.3 1.5]


In [32]:
#30. How to find common values between two arrays? 
arr1 = np.array([0,1,2,3,4])
arr2 = np.array([1,3,4])

print(np.intersect1d(arr1, arr2))

[1 3 4]
