In [2]:
import numpy as np

In [ ]:
#31. How to ignore all numpy warnings (not recommended)?


In [3]:
#32. Is the following expressions true? (★☆☆)
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\User 1\AppData\Local\Temp\ipykernel_10244\1918579400.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

In [6]:
#33. How to get the dates of yesterday, today and tomorrow?
from datetime import datetime, timedelta

presentday = datetime.now()
yesterday = presentday - timedelta(1)
tomorrow = presentday + timedelta(1)

print("Present Day: ",presentday)
print("Yesterday: ",yesterday)
print("Tomorrow: ", tomorrow)

Present Day:  2024-10-23 12:36:44.827674
Yesterday:  2024-10-22 12:36:44.827674
Tomorrow:  2024-10-24 12:36:44.827674


In [8]:
#33. How to get the dates of yesterday, today and tomorrow?
yesterday = np.datetime64('today', 'D')
today = np.datetime64('today','D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1,'D')

print("Today: ",today)
print("Yesterday: ",yesterday)
print("Tomorrow: ", tomorrow)

Today:  2024-10-23
Yesterday:  2024-10-23
Tomorrow:  2024-10-24


In [14]:
#34. How to get all the dates corresponding to the month of July 2016?
print("July, 2016")
print(np.arange('2016-03','2016-04', dtype= 'datetime64[D]'))

July, 2016
['2016-03-01' '2016-03-02' '2016-03-03' '2016-03-04' '2016-03-05'
 '2016-03-06' '2016-03-07' '2016-03-08' '2016-03-09' '2016-03-10'
 '2016-03-11' '2016-03-12' '2016-03-13' '2016-03-14' '2016-03-15'
 '2016-03-16' '2016-03-17' '2016-03-18' '2016-03-19' '2016-03-20'
 '2016-03-21' '2016-03-22' '2016-03-23' '2016-03-24' '2016-03-25'
 '2016-03-26' '2016-03-27' '2016-03-28' '2016-03-29' '2016-03-30'
 '2016-03-31']


In [ ]:
#35. How to compute ((A+B)*(-A/2)) in place (without copy)?


In [ ]:
#36. Extract the integer part of a random array of positive numbers using 4 different methods 


In [22]:
#37. Create a 5x5 matrix with row values ranging from 0 to 4
arr = np.zeros((5,5))
print("Initial array")
print(arr)

arr += np.arange(5)
print("Row values")
print(arr)

Initial array
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [25]:
#38. Consider a generator function that generates 10 integers and use it to build an array
integers = (x for x in range (10))
print(np.fromiter(integers, np.int64))

[0 1 2 3 4 5 6 7 8 9]


In [27]:
#39. Create a vector of size 10 with values ranging from 0 to 1, both excluded 
x = np.linspace(0,1,12,endpoint=True)
print(x)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]


In [31]:
#40. Create a random vector of size 10 and sort it
vector = np.random.random(10)
print("Original array")
print(vector)

vector.sort()
print("Sorted Array")
print(vector)

Original array
[0.43588473 0.64105218 0.73985901 0.36230967 0.7138067  0.23386484
 0.25715927 0.95825328 0.60122295 0.89219223]
Sorted Array
[0.23386484 0.25715927 0.36230967 0.43588473 0.60122295 0.64105218
 0.7138067  0.73985901 0.89219223 0.95825328]


In [40]:
#41. How to sum a small array faster than np.sum? 
arr = np.ones((5,5))
print(arr)

sum = np.sum(arr)
print(sum)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
25.0
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [45]:
#42. Consider two random array A and B, check if they are equal 
A = np.random.random(7)
B = np.random.random(7)


print(A)
print(B)
print( A == B)

[0.71671552 0.21213715 0.52194905 0.66448263 0.73536648 0.54940932
 0.4191021 ]
[0.71974334 0.61766738 0.91108089 0.00658416 0.79026243 0.26177609
 0.035661  ]
[False False False False False False False]


In [ ]:
#43. Make an array immutable (read-only)


In [ ]:
#44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates


In [ ]:
#45. Create random vector of size 10 and replace the maximum value by 0