In [1]:
import numpy as np

In [3]:
#2 Print the numpy version and the configuration 
np.__version__

'2.1.2'

In [3]:
#3. Create a null vector of size 10 
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
#4. How to find the memory size of any array
print("Size of the arr: ", arr.size)
print("Memory Size of the arr element in bytes: ", arr.itemsize)

Size of the arr:  10
Memory Size of the arr element in bytes:  8


In [ ]:

#5. How to get the documentation of the numpy add function from the command line?
 

In [10]:
#6. Create a null vector of size 10 but the fifth value which is 1 
arr1 = np.eye(10)[5-1]
print(arr1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [12]:

#7. Create a vector with values ranging from 10 to 49
arr2 = np.arange(10,50)
print(arr2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [17]:
#8. Reverse a vector (first element becomes last)
arr3 = np.arange(12,21)
print("Original array: ", arr3)

arr3 = arr3[::-1]
print("Reverted array: ", arr3)

Original array:  [12 13 14 15 16 17 18 19 20]
Reverted array:  [20 19 18 17 16 15 14 13 12]


In [21]:
#9. Create a 3x3 matrix with values ranging from 0 to 8
arr4 = np.arange(0,9).reshape(3,3)
print(arr4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#10. Find indices of non-zero elements from [1,2,0,0,4,0]


In [3]:
#11. Create a 3x3 identity matrix
arr6 = np.identity(3)
print(arr6)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
#12. Create 3x3 array with random values
arr7 = np.random.random((3,3))
print(arr7)

[[0.15817348 0.45398425 0.14768205]
 [0.91767886 0.76674351 0.19860444]
 [0.19886787 0.58018877 0.2725978 ]]


In [15]:
#13. Create a 10x10 array with random values and find the minimum and maximum values
arr8 = np.random.random((10,10))
print(arr8)
print(np.max(arr8))
print(np.min(arr8))

[[0.48750871 0.51192493 0.69642257 0.54596624 0.72494179 0.18503741
  0.04702738 0.00982971 0.49740934 0.50145545]
 [0.85284846 0.65515552 0.82733335 0.01993664 0.46824704 0.94907383
  0.12658724 0.02649592 0.35354265 0.23802217]
 [0.41506592 0.67349332 0.80913578 0.1166758  0.21203489 0.60154186
  0.3656654  0.70781769 0.05669992 0.59367347]
 [0.616506   0.90148915 0.9153583  0.19325069 0.29337624 0.32970699
  0.45168716 0.60040987 0.49909978 0.9630973 ]
 [0.38936022 0.99638028 0.66327257 0.63728368 0.70846135 0.84313433
  0.92167869 0.72930709 0.24342978 0.39782774]
 [0.65467015 0.42555583 0.80865487 0.13484527 0.25769238 0.22606247
  0.59593213 0.32420375 0.41905768 0.1650415 ]
 [0.80552853 0.19253307 0.58029528 0.25161407 0.14212824 0.15578793
  0.83083213 0.80619815 0.68397685 0.09629372]
 [0.29255736 0.24414794 0.21695656 0.13199851 0.2861485  0.95494815
  0.81696027 0.32824711 0.09438523 0.89677872]
 [0.2551972  0.10195325 0.68687734 0.85983638 0.76798411 0.36518624
  0.45478003

In [17]:
#14. Create a rondom vector of size 30 and find the mean value
arr9 = np.random.random(10)
print(arr9)

print(np.mean(arr9))

[0.59371652 0.96411444 0.04806874 0.60608766 0.88839463 0.61452036
 0.18252261 0.38375377 0.03020542 0.47532226]
0.47867064000646886


In [18]:
#15. Create a 2d array with 1 on the border and 0 inside 
arr10 = np.ones((5,5))

arr10[1:-1, 1:-1] = 0
print(arr10)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
